# Generated by Django 5.0.6 on 2024-05-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='adres',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='kodpocztowy',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='miasto',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='nazwisko',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='nr_telefonu',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='created_at',
            new_name='utworzono',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='wojewodztwo',
        ),
    ]
