# Generated by Django 5.0.6 on 2024-05-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_address_record_adres_rename_city_record_imie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='kodpocztowy',
            new_name='kod_pocztowy',
        ),
    ]
